### ISSUE TITLE
Null pointer execption when subscribing message

### ISSUE THREAD

**Issue by juyahn** [dist-sys/mqttloader#32]
Hi, while checking the latency, I noticed that mqttloader sometimes displays the error message shown below and doesn't receive any messages.

```
$ /home/mqttloader/bin/mqttloader -c "/home/mqttloader/mqtt-subscriber.conf"
Exception in thread "Thread-5" java.lang.NullPointerException
        at mqttloader.Util.getEpochMicros(Util.java:153)
        at mqttloader.Recorder.run(Recorder.java:66)
        at java.base/java.lang.Thread.run(Thread.java:829)

Measurement started: 2023-03-07 17:44:29.780 KST
Measurement ended: 2023-03-07 17:44:39.888 KST

-----Publisher-----
Maximum throughput [msg/s]: 0
Average throughput [msg/s]: 0.000
Number of published messages: 0
Per second throughput [msg/s]:

-----Subscriber-----
Maximum throughput [msg/s]: 0
Average throughput [msg/s]: 0.000
Number of received messages: 0
Per second throughput [msg/s]:
Maximum latency [ms]: 0.000
Average latency [ms]: 0.000
```
This happens quite frequently but not always. Do you have any ideas on how to solve this?
Here's my conf file.

```
# mqtt-publisher.conf
broker = 
broker_port = 

num_publishers = 1
num_subscribers = 0

payload = 64 
interval = 1000000 
exec_time = 60


# mqtt-subscriber.conf
broker = 
broker_port = 

num_publishers = 0
num_subscribers = 1

exec_time = 60
subscriber_timeout = 60

output = 
```

**Comment by nabon** [comment]
Sorry for the very late reply.
I found that the NullPointerException problem could occur when using the "output" parameter.
The problem was fixed in v0.8.6.
I appreciate your detailed information that helps us to improve MQTTLoader.
